version: '3.8'

services:
  backend:
    build:
      context: ./Back-End
    volumes:
      - ./Back-End:/var/www/html
    ports:
      - "9000:90"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Front-End/dist:/usr/share/nginx/html 
    depends_on:
      - backend

