version: '3.8'

services:

  backend:
    build:
      context: ./Back-End
    ports:
    - "9000:80"
    volumes:
      - ./Back-End/app:/var/www/html
    
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Front-End/dist:/usr/share/nginx/html 
    depends_on:
      - backend

  db:
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_DATABASE: e-motions
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./Back-End/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1

