version: '3.8'

services:
  app:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    volumes:
      - ./Back-End:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Back-End:/var/www/html
    depends_on:
      - app
